id: I9CF57338
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:26:06+00:00'
last_modified: '2022-06-07T13:40:13.753676+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017328
  title: ལམ་སྟོན་སྒྲོན་མེའི་ཕྲེང་བ། ༼༢༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    72EE:
      image_group_id: I00EGS1017330
      title: ''
      total_pages: 274
      order: 1
      base_file: 72EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
