id: I9CF57338
legacy_id: P000767
ocr_import_info:
  bdrc_scan_id: W00EGS1017328
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T15:24:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:07:09.424534+00:00'
last_modified: 2022-08-29 19:07:40.974412
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017328
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017328
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་སྟོན་སྒྲོན་མེའི་ཕྲེང་བ། ༼༢༽
statistics:
  ocr_word_mean_confidence_index: 0.9586869297273594
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I00EGS1017330:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017330
      total_pages: 274
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017330.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9586869297273594
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
