id: P000767
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:01:56.993562
source_metadata:
  id: bdr:W00EGS1017328
  title: ལམ་སྟོན་སྒྲོན་མེའི་ཕྲེང་བ། ༼༢༽
  author: ''
  volumes:
    be1079e5c12040d58aa8306bb9aba36a:
      image_group_id: I00EGS1017330
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
